name: fme-unit-tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
          cache: "pip"
          cache-dependency-path: |
            requirements_except_torch.txt
            requirements_outside_of_docker.txt
            requirements_no_deps.txt
            fme/dev-requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          make install_dependencies
          make install_local_packages
      - name: Run pytest
        run: |
          make test_fme_unit_tests
